name: Test & Publish NPM Packages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  packages: write

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@${{ github.repository_owner }}'
        
    - name: Install dependencies - Payment
      working-directory: ./payment
      run: |
        npm install
        # Verificar que jest est치 instalado
        npm list jest || npm list @types/jest || echo "Jest dependencies check"
        
    - name: Install dependencies - ATM  
      working-directory: ./atm
      run: |
        npm install
        # Verificar que jest est치 instalado
        npm list jest || npm list @types/jest || echo "Jest dependencies check"
        
    - name: Fix permissions and run tests - Payment
      working-directory: ./payment
      run: |
        # Dar permisos de ejecuci칩n a los binarios de node_modules
        chmod +x node_modules/.bin/* || true
        # Ejecutar tests usando npm (que maneja mejor los paths)
        npm run test:cov
      
    - name: Fix permissions and run tests - ATM
      working-directory: ./atm  
      run: |
        # Dar permisos de ejecuci칩n a los binarios de node_modules
        chmod +x node_modules/.bin/* || true
        # Ejecutar tests usando npm (que maneja mejor los paths)
        npm run test:cov
        
    - name: Update package.json - Payment
      working-directory: ./payment
      run: |
        npm pkg set name="@upt-faing-epis/payment_jersonch"
        npm pkg set version="1.0.${{ github.run_number }}"
        npm pkg set repository.url="git+https://github.com/UPT-FAING-EPIS/lab-2025-i-pds-u2-03-nest-JersonCh.git"
        npm pkg set publishConfig.registry="https://npm.pkg.github.com"
        npm pkg set publishConfig.access="public"
        
    - name: Update package.json - ATM
      working-directory: ./atm
      run: |
        npm pkg set name="@upt-faing-epis/atm_jersonch"
        npm pkg set version="1.0.${{ github.run_number }}"
        npm pkg set repository.url="git+https://github.com/UPT-FAING-EPIS/lab-2025-i-pds-u2-03-nest-JersonCh.git"
        npm pkg set publishConfig.registry="https://npm.pkg.github.com"
        npm pkg set publishConfig.access="public"
        
    - name: Build packages
      run: |
        cd payment && npm run build
        cd ../atm && npm run build
        
    - name: Publish to GitHub Packages - Payment
      working-directory: ./payment
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
        
    - name: Publish to GitHub Packages - ATM
      working-directory: ./atm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true