name: Test & Publish NPM Packages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@${{ github.repository_owner }}'
        
    - name: Install dependencies - Payment
      working-directory: ./payment
      run: npm install  # Cambiar npm ci por npm install
      
    - name: Install dependencies - ATM
      working-directory: ./atm
      run: npm install  # Cambiar npm ci por npm install
      
    - name: Run tests with coverage - Payment
      working-directory: ./payment
      run: npm run test:cov
      
    - name: Run tests with coverage - ATM
      working-directory: ./atm
      run: npm run test:cov
        
    - name: Update package.json - Payment
      working-directory: ./payment
      run: |
        npm pkg set name="@upt-faing-epis/payment_jersonch"
        npm pkg set version="1.0.${{ github.run_number }}"
        npm pkg set repository.url="git+https://github.com/UPT-FAING-EPIS/lab-2025-i-pds-u2-03-nest-JersonCh.git"
        npm pkg set publishConfig.registry="https://npm.pkg.github.com"
        npm pkg set publishConfig.access="public"
        
    - name: Update package.json - ATM
      working-directory: ./atm
      run: |
        npm pkg set name="@upt-faing-epis/atm_jersonch"
        npm pkg set version="1.0.${{ github.run_number }}"
        npm pkg set repository.url="git+https://github.com/UPT-FAING-EPIS/lab-2025-i-pds-u2-03-nest-JersonCh.git"
        npm pkg set publishConfig.registry="https://npm.pkg.github.com"
        npm pkg set publishConfig.access="public"
        
    - name: Build packages
      run: |
        cd payment && npm run build
        cd ../atm && npm run build
        
    - name: Publish to GitHub Packages - Payment
      working-directory: ./payment
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish to GitHub Packages - ATM
      working-directory: ./atm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}